//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllCorporateAllServices
    {
        public Nullable<System.Guid> AccountNameGuid { get; set; }
        public Nullable<System.Guid> ServiceNameGuid { get; set; }
        public string AccountName { get; set; }
        public string ServiceName { get; set; }
        public long OrderKey { get; set; }
    }
}
