//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_package_table
    {
        public int id { get; set; }
        public decimal level_id { get; set; }
        public int table_id { get; set; }
        public int relation_type { get; set; }
    
        public virtual app_package app_package { get; set; }
        public virtual app_table app_table { get; set; }
    }
}
