//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_column
    {
        public int id { get; set; }
        public int table_id { get; set; }
        public string tab_schema { get; set; }
        public string tab_name { get; set; }
        public string col_name { get; set; }
        public string col_type { get; set; }
        public Nullable<int> col_length { get; set; }
        public bool is_nullable { get; set; }
        public Nullable<int> ordinal_position { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
    
        public virtual app_table app_table { get; set; }
    }
}
