//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_crm_field
    {
        public int id { get; set; }
        public string crm_entity { get; set; }
        public string crm_section { get; set; }
        public string label { get; set; }
        public string batch_integration_field { get; set; }
        public string crm_field { get; set; }
        public string db2_field { get; set; }
        public string web_service_field { get; set; }
        public bool is_used_on_crm { get; set; }
        public string remarks { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public string tags { get; set; }
        public bool is_web_service_field { get; set; }
    }
}
