//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_organization_structure
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string org_name { get; set; }
        public string org_type { get; set; }
        public short org_level { get; set; }
        public bool show { get; set; }
        public string org_code { get; set; }
    }
}
