//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_customer_interaction
    {
        public int id_row { get; set; }
        public bool include_in_run { get; set; }
        public string Flag { get; set; }
        public string Company { get; set; }
        public string Customer { get; set; }
        public string CustomerInteraction { get; set; }
        public string CustomerMood { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string InteractionChannel { get; set; }
        public string InteractionDescription { get; set; }
        public string InteractionType { get; set; }
        public string Lead { get; set; }
        public string Name { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> OwnerIDType { get; set; }
    }
}
