//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_investment
    {
        public int id_row { get; set; }
        public bool include_in_run { get; set; }
        public string investment_number { get; set; }
        public string product { get; set; }
        public string product_group { get; set; }
        public string currency { get; set; }
        public Nullable<int> currency_type { get; set; }
        public string security { get; set; }
        public string bank { get; set; }
        public Nullable<int> total_units { get; set; }
        public Nullable<int> pledged_units { get; set; }
        public Nullable<int> available_units { get; set; }
        public Nullable<decimal> current_market_price { get; set; }
        public Nullable<double> current_ltv_perc { get; set; }
        public Nullable<double> allowed_ltv_perc { get; set; }
        public Nullable<decimal> weighted_price { get; set; }
        public Nullable<decimal> acquisition_cost { get; set; }
        public Nullable<double> current_market_value { get; set; }
        public Nullable<double> profit_or_loss_perc { get; set; }
        public Nullable<System.DateTime> current_price_date { get; set; }
        public string type_of_investment { get; set; }
        public string investor_profiling_performed { get; set; }
        public Nullable<System.DateTime> date_of_investor_profiling { get; set; }
        public string investor_profiling_survey { get; set; }
        public Nullable<System.DateTime> date_of_next_investor_profiling { get; set; }
        public string asset_allocation_preferences { get; set; }
        public string investment_objective { get; set; }
        public string investment_experience { get; set; }
        public string time_horizon { get; set; }
        public string liquidity_preference { get; set; }
        public string growth_preference { get; set; }
        public Nullable<bool> has_investment_account { get; set; }
        public string wealth_creation_objective { get; set; }
        public string retirement_objective { get; set; }
        public string safety_objective { get; set; }
        public string risk_tolerance { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> tenor { get; set; }
        public string customer { get; set; }
        public string company { get; set; }
        public string flag { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> OwnerIDType { get; set; }
    }
}
