//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_loans_loans
    {
        public int id_row { get; set; }
        public bool include_in_run { get; set; }
        public string flag { get; set; }
        public Nullable<decimal> account_balance { get; set; }
        public string account_no { get; set; }
        public string bank { get; set; }
        public string claimant_beneficiary { get; set; }
        public Nullable<int> collection_risk { get; set; }
        public string currency { get; set; }
        public Nullable<int> currency_type { get; set; }
        public string customer { get; set; }
        public string debt_type { get; set; }
        public Nullable<decimal> disbursed_amount { get; set; }
        public Nullable<decimal> total_disbursement_amount { get; set; }
        public Nullable<System.DateTime> disbursement_date { get; set; }
        public Nullable<decimal> down_payment { get; set; }
        public Nullable<decimal> initial_loan_amount { get; set; }
        public Nullable<decimal> installment_amount { get; set; }
        public Nullable<decimal> interest_penalty_interest_amount_arrears { get; set; }
        public Nullable<decimal> interest_amount { get; set; }
        public Nullable<double> interest_rate { get; set; }
        public string interest_rate_base_margin { get; set; }
        public Nullable<decimal> interest_repayment_amount { get; set; }
        public string interest_repayment_frequency { get; set; }
        public Nullable<int> is_early_repayment_allowed { get; set; }
        public Nullable<decimal> last_payment_amount { get; set; }
        public Nullable<System.DateTime> last_payment_date { get; set; }
        public Nullable<System.DateTime> loan_maturity_date { get; set; }
        public string loan_number { get; set; }
        public Nullable<System.DateTime> loan_start_date { get; set; }
        public Nullable<int> loan_type { get; set; }
        public Nullable<System.DateTime> next_installment_date { get; set; }
        public Nullable<decimal> next_payment_amount { get; set; }
        public Nullable<System.DateTime> next_payment_date { get; set; }
        public Nullable<decimal> original_amount { get; set; }
        public Nullable<System.DateTime> out_of_order_since { get; set; }
        public Nullable<decimal> outstanding_principal_amount { get; set; }
        public Nullable<decimal> outstanding_total_amount { get; set; }
        public Nullable<int> payback_months { get; set; }
        public Nullable<double> penalty_interest_rate { get; set; }
        public Nullable<decimal> principal_amount { get; set; }
        public Nullable<decimal> principal_amount_arrears { get; set; }
        public Nullable<decimal> principal_repayment_amount { get; set; }
        public string principal_repayment_frequency { get; set; }
        public string product { get; set; }
        public string product_group { get; set; }
        public string purpose_of_loan { get; set; }
        public Nullable<double> rate_perc { get; set; }
        public string restructuring { get; set; }
        public Nullable<decimal> security_value { get; set; }
        public Nullable<int> tenor { get; set; }
        public Nullable<int> status { get; set; }
        public string company { get; set; }
        public Nullable<decimal> outstanding_amount { get; set; }
        public Nullable<decimal> amount_past_due { get; set; }
        public Nullable<decimal> amount_past_due_interest { get; set; }
        public Nullable<decimal> repayment_amount { get; set; }
        public string repayment_frequency { get; set; }
        public Nullable<decimal> arrears { get; set; }
        public string domain_name { get; set; }
        public Nullable<int> owneridtype { get; set; }
    }
}
