//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMEntities : DbContext
    {
        public CRMEntities()
            : base("name=CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<app_column> app_column { get; set; }
        public virtual DbSet<app_table> app_table { get; set; }
        public virtual DbSet<app_user> app_user { get; set; }
        public virtual DbSet<SSISErrorTable> SSISErrorTable { get; set; }
        public virtual DbSet<SSISErrorTableLog> SSISErrorTableLog { get; set; }
        public virtual DbSet<AllCorporateAllServices> AllCorporateAllServices { get; set; }
        public virtual DbSet<core_corporate_customer> core_corporate_customer { get; set; }
        public virtual DbSet<Monitoring> Monitoring { get; set; }
        public virtual DbSet<MonitoringLog> MonitoringLog { get; set; }
        public virtual DbSet<restricted_code_bu_mapping> restricted_code_bu_mapping { get; set; }
        public virtual DbSet<SSIS_Configurations> SSIS_Configurations { get; set; }
        public virtual DbSet<vrp_collateral> vrp_collateral { get; set; }
        public virtual DbSet<vrp_corporate_customer> vrp_corporate_customer { get; set; }
        public virtual DbSet<vrp_credit_card> vrp_credit_card { get; set; }
        public virtual DbSet<vrp_credit_card_account> vrp_credit_card_account { get; set; }
        public virtual DbSet<vrp_current_savings> vrp_current_savings { get; set; }
        public virtual DbSet<vrp_debit_card> vrp_debit_card { get; set; }
        public virtual DbSet<vrp_fixed_deposit> vrp_fixed_deposit { get; set; }
        public virtual DbSet<vrp_joint_holders_connections> vrp_joint_holders_connections { get; set; }
        public virtual DbSet<vrp_loans_loans> vrp_loans_loans { get; set; }
        public virtual DbSet<vrp_PluginSteps> vrp_PluginSteps { get; set; }
        public virtual DbSet<vrp_product> vrp_product { get; set; }
        public virtual DbSet<vrp_retail_customer> vrp_retail_customer { get; set; }
        public virtual DbSet<vrp_treasury> vrp_treasury { get; set; }
        public virtual DbSet<app_package> app_package { get; set; }
        public virtual DbSet<RunHistoryView> RunHistoryView { get; set; }
        public virtual DbSet<TodayRunView> TodayRunView { get; set; }
        public virtual DbSet<MonitoringView> MonitoringView { get; set; }
    }
}
