//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoring
    {
        public decimal levelid { get; set; }
        public string LevelName { get; set; }
        public string LevelType { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public long rowindex { get; set; }
        public long Core_Count { get; set; }
        public long Vrp_Count { get; set; }
        public bool IsLastRun { get; set; }
    }
}
