//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunHistoryView
    {
        public System.DateTime rundate { get; set; }
        public Nullable<System.DateTime> started { get; set; }
        public Nullable<System.DateTime> completed { get; set; }
        public Nullable<int> num_errors { get; set; }
        public Nullable<int> duration_seconds { get; set; }
        public Nullable<long> numRows { get; set; }
    }
}
