//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSISErrorTable
    {
        public System.Guid recid { get; set; }
        public string packageName { get; set; }
        public string primaryKeyName { get; set; }
        public string primaryKeyValue { get; set; }
        public string code { get; set; }
        public string errordesc { get; set; }
        public string errorcolumn { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<decimal> levelid { get; set; }
        public long rowindex { get; set; }
        public string recorddata { get; set; }
        public Nullable<int> id_row { get; set; }
    }
}
