//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_currency
    {
        public int id_row { get; set; }
        public string vrp_CurrencyCode { get; set; }
        public string vrp_CurrencyName { get; set; }
        public string vrp_CurrencySymbol { get; set; }
        public string vrp_CurrencyPrecision { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<System.Guid> Guid_Currency { get; set; }
        public string flag { get; set; }
    }
}
