//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_fixed_deposit
    {
        public string Flag { get; set; }
        public Nullable<decimal> BlockedAmount { get; set; }
        public Nullable<decimal> BookBalance { get; set; }
        public string Branch { get; set; }
        public string ClaimantBeneficiary { get; set; }
        public string CurrencyType { get; set; }
        public string Customer { get; set; }
        public Nullable<int> IsJoint { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<double> OdBaseRate { get; set; }
        public Nullable<decimal> OdLimit { get; set; }
        public string OdLimitCurrency { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public string Product { get; set; }
        public string ProductGroup { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> UnclearedBalance { get; set; }
        public string Currency { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> AvailableBalance { get; set; }
        public Nullable<decimal> AverageBalance { get; set; }
        public string Bank { get; set; }
        public Nullable<int> TotalNoOfTtDdMcTransaction { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Term { get; set; }
        public Nullable<decimal> BalanceAtMaturity { get; set; }
        public Nullable<decimal> ProjectedInterestAmount { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public string MaturityInstructionDetails { get; set; }
        public string FacilityId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTime> NextPaymentDate { get; set; }
        public Nullable<int> InterestFrequency { get; set; }
        public Nullable<System.DateTime> OutOfOrderSince { get; set; }
        public Nullable<decimal> BlockedFunds { get; set; }
        public string BlockedReasons { get; set; }
        public string InformativeMarkers { get; set; }
        public Nullable<bool> AccountSweep { get; set; }
        public Nullable<bool> Compensation { get; set; }
        public Nullable<double> PenaltyInterest { get; set; }
        public Nullable<System.Guid> BankGuid { get; set; }
        public Nullable<System.Guid> BranchGuid { get; set; }
        public Nullable<System.Guid> ClaimantGuid { get; set; }
        public Nullable<System.Guid> CompanyGuid { get; set; }
        public Nullable<System.Guid> CurrencyGuid { get; set; }
        public Nullable<System.Guid> CustomerGuid { get; set; }
        public Nullable<System.Guid> ProductGuid { get; set; }
        public Nullable<System.Guid> ProductGroupGuid { get; set; }
        public Nullable<System.Guid> PrimaryKeyGuid { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> OwnerIDType { get; set; }
        public Nullable<System.Guid> DomainNameGuid { get; set; }
        public Nullable<System.Guid> OdLimitCurrencyGuid { get; set; }
        public Nullable<bool> IsCollateral { get; set; }
        public long OrderKey { get; set; }
    }
}
