//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_trade_finance_products
    {
        public int id_row { get; set; }
        public string flag { get; set; }
        public string currency { get; set; }
        public Nullable<System.Guid> GuidCurrency { get; set; }
        public string company { get; set; }
        public Nullable<System.Guid> GuidCompany { get; set; }
        public string accountnumber { get; set; }
        public string claimantbeneficiary { get; set; }
        public Nullable<System.Guid> claimantbeneficiary_guid { get; set; }
        public Nullable<int> currencytype { get; set; }
        public string customer { get; set; }
        public Nullable<System.Guid> GuidCustomer { get; set; }
        public string product { get; set; }
        public Nullable<System.Guid> GuidProduct { get; set; }
        public string productgroup { get; set; }
        public Nullable<System.Guid> Guidproductgroup { get; set; }
        public Nullable<System.DateTime> openingdate { get; set; }
        public Nullable<System.DateTime> expirydate { get; set; }
        public Nullable<decimal> totalamount { get; set; }
        public string beneficiarycountry { get; set; }
        public Nullable<System.Guid> GuidBeneficiarycountry { get; set; }
        public string branch { get; set; }
        public Nullable<System.Guid> GuidBranch { get; set; }
        public Nullable<decimal> totalamountinlocalcurrency { get; set; }
        public Nullable<decimal> outstandingamount { get; set; }
        public Nullable<decimal> outstandingamountinlocalcurrency { get; set; }
        public string bank { get; set; }
        public Nullable<System.Guid> Guidbank { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> automaticrenewal { get; set; }
        public string beneficiaryname { get; set; }
        public Nullable<System.Guid> GuidPrimarykey { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> OwnerIDType { get; set; }
        public Nullable<System.Guid> DomainNameGuid { get; set; }
    }
}
