//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_treasury
    {
        public string flag { get; set; }
        public string account_number { get; set; }
        public Nullable<System.Guid> account_number_guid { get; set; }
        public string company { get; set; }
        public Nullable<System.Guid> company_guid { get; set; }
        public string product { get; set; }
        public Nullable<System.Guid> product_guid { get; set; }
        public string product_group { get; set; }
        public Nullable<System.Guid> product_group_guid { get; set; }
        public Nullable<int> fx_type { get; set; }
        public Nullable<System.DateTime> exercise_date { get; set; }
        public string contract_number { get; set; }
        public Nullable<decimal> contract_amount { get; set; }
        public Nullable<System.DateTime> contract_date { get; set; }
        public string counterparty { get; set; }
        public Nullable<decimal> strike_price { get; set; }
        public string bank { get; set; }
        public Nullable<System.Guid> bank_guid { get; set; }
        public Nullable<int> status { get; set; }
        public string domain_name { get; set; }
        public Nullable<System.Guid> domain_name_guid { get; set; }
        public Nullable<int> owneridtype { get; set; }
        public long OrderKey { get; set; }
    }
}
