//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_joint_account
    {
        public int id_row { get; set; }
        public string flag { get; set; }
        public string customer { get; set; }
        public Nullable<System.Guid> customerGuid { get; set; }
        public string accountnumber { get; set; }
        public Nullable<System.Guid> accountnumberGuid { get; set; }
        public Nullable<System.Guid> primarykeyGuid { get; set; }
    }
}
