//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_bank_assurance
    {
        public int id_row { get; set; }
        public string flag { get; set; }
        public string ins_policy_id { get; set; }
        public Nullable<int> type { get; set; }
        public string policy_name { get; set; }
        public Nullable<System.DateTime> contract_date { get; set; }
        public Nullable<System.DateTime> maturity_date { get; set; }
        public string ccy_code { get; set; }
        public Nullable<System.Guid> ccy_code_guid { get; set; }
        public Nullable<int> ccy_type { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string customer_main_insured { get; set; }
        public Nullable<System.Guid> customer_main_insured_guid { get; set; }
        public string company_main_insured { get; set; }
        public Nullable<System.Guid> company_main_insured_guid { get; set; }
        public string customer_joint_insured { get; set; }
        public Nullable<System.Guid> customer_joint_insured_guid { get; set; }
        public string company_joint_insured { get; set; }
        public Nullable<System.Guid> company_joint_insured_guid { get; set; }
        public string bank { get; set; }
        public Nullable<System.Guid> bank_guid { get; set; }
        public Nullable<int> status { get; set; }
        public string policy_number { get; set; }
        public string product { get; set; }
        public Nullable<System.Guid> product_guid { get; set; }
        public string product_group { get; set; }
        public Nullable<System.Guid> product_group_guid { get; set; }
        public Nullable<decimal> sum_insured { get; set; }
        public string insurance_company { get; set; }
        public Nullable<System.Guid> insurance_company_guid { get; set; }
        public string owner { get; set; }
        public Nullable<int> owneridtype { get; set; }
        public Nullable<System.Guid> primary_key { get; set; }
    }
}
