//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_joint_holders_connections
    {
        public string Flag { get; set; }
        public string ConnectFromId { get; set; }
        public string ConnectToId { get; set; }
        public Nullable<int> ConnectToTypeCode { get; set; }
        public Nullable<System.Guid> ConnectFromIdGuid { get; set; }
        public Nullable<System.Guid> ConnectToIdGuid { get; set; }
        public Nullable<System.Guid> PrimaryKeyGuid { get; set; }
        public Nullable<System.Guid> RoleIdGuid { get; set; }
        public string RoleId { get; set; }
        public Nullable<int> ConnectFromTypeCode { get; set; }
        public long OrderKey { get; set; }
        public int id_row { get; set; }
    }
}
