//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_retail_segment
    {
        public int id_row { get; set; }
        public string vrp_Id { get; set; }
        public string vrp_Name { get; set; }
        public Nullable<System.Guid> Guid_RetailSegment { get; set; }
        public string flag { get; set; }
    }
}
