//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_campaign_response
    {
        public int id_row { get; set; }
        public string Name { get; set; }
        public string Campaign { get; set; }
        public Nullable<System.Guid> Campaign_guid { get; set; }
        public string Campaign_Activity { get; set; }
        public Nullable<System.Guid> Campaign_Activity_guid { get; set; }
        public string Customer { get; set; }
        public Nullable<System.Guid> Customer_guid { get; set; }
        public string Direct_Channel_Activity { get; set; }
        public Nullable<System.Guid> Direct_Channel_Activity_guid { get; set; }
        public Nullable<int> Response_Value { get; set; }
        public Nullable<System.DateTime> Response_Date { get; set; }
        public string Email { get; set; }
    }
}
