//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_corporate_group
    {
        public int id_row { get; set; }
        public string Flag { get; set; }
        public string CorporateGroupCode { get; set; }
        public string CorporateGroupName { get; set; }
        public Nullable<System.Guid> PrimaryKeyGuid { get; set; }
    }
}
