//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_power_of_attorney
    {
        public int id_row { get; set; }
        public string Flag { get; set; }
        public string Company_POA { get; set; }
        public string Customer_POA { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string RepresentedPerson { get; set; }
        public string RepresentedCompany { get; set; }
        public Nullable<int> POAScope { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.Guid> CompanyPOAGuid { get; set; }
        public Nullable<System.Guid> CustomerPOAGuid { get; set; }
        public Nullable<System.Guid> RepresentedPersonGuid { get; set; }
        public Nullable<System.Guid> RepresentedCompanyGuid { get; set; }
        public Nullable<System.Guid> AccountNumberGuid { get; set; }
        public Nullable<System.Guid> PowerOfAttorneyGuid { get; set; }
        public string POA_Name { get; set; }
        public string DomainName { get; set; }
        public Nullable<System.Guid> DomainNameGuid { get; set; }
        public Nullable<int> OwnerIDType { get; set; }
    }
}
