//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_corporate_customer
    {
        public string cif { get; set; }
        public Nullable<System.Guid> cif_guid { get; set; }
        public string county { get; set; }
        public string line_1 { get; set; }
        public string line_2 { get; set; }
        public string line_3 { get; set; }
        public string zip_postal_code { get; set; }
        public string post_office_box { get; set; }
        public string state_province { get; set; }
        public Nullable<bool> do_not_allow_bulk_emails { get; set; }
        public Nullable<bool> do_not_allow_emails { get; set; }
        public Nullable<bool> do_not_allow_faxes { get; set; }
        public Nullable<bool> do_not_allow_phone_calls { get; set; }
        public Nullable<bool> do_not_allow_mails { get; set; }
        public Nullable<bool> send_marketing_materials { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public Nullable<int> industry { get; set; }
        public Nullable<System.DateTime> last_date_included_in_campaign { get; set; }
        public string company_name { get; set; }
        public Nullable<int> no_of_employees { get; set; }
        public string originating_lead { get; set; }
        public Nullable<System.Guid> originating_lead_guid { get; set; }
        public Nullable<int> ownership { get; set; }
        public string parent_company { get; set; }
        public Nullable<System.Guid> parent_company_guid { get; set; }
        public Nullable<int> preferred_method_of_contact { get; set; }
        public string primary_contact { get; set; }
        public Nullable<System.Guid> primary_contact_guid { get; set; }
        public string main_phone { get; set; }
        public string ticker_symbol { get; set; }
        public string city { get; set; }
        public Nullable<System.Guid> city_guid { get; set; }
        public Nullable<double> company_turnover_month { get; set; }
        public string corporate_segment { get; set; }
        public Nullable<System.Guid> corporate_segment_guid { get; set; }
        public Nullable<int> fitch_long_term { get; set; }
        public Nullable<int> fitch_short_term { get; set; }
        public Nullable<bool> in_liquidation { get; set; }
        public Nullable<System.DateTime> last_interaction_date { get; set; }
        public Nullable<int> moody_long_term { get; set; }
        public Nullable<int> moody_short_term { get; set; }
        public Nullable<int> no_of_offices_branches { get; set; }
        public Nullable<int> number_of_active_products { get; set; }
        public Nullable<int> number_of_products { get; set; }
        public Nullable<int> operation_mode { get; set; }
        public string relationship_manager { get; set; }
        public Nullable<System.Guid> relationship_manager_guid { get; set; }
        public Nullable<int> relationship_status { get; set; }
        public string sector { get; set; }
        public Nullable<System.Guid> sector_guid { get; set; }
        public string special_codes { get; set; }
        public Nullable<int> s_and_p_long_term { get; set; }
        public Nullable<int> s_and_p_short_term { get; set; }
        public Nullable<decimal> total_fund_based_exposure { get; set; }
        public Nullable<decimal> total_limits { get; set; }
        public Nullable<decimal> total_credit { get; set; }
        public Nullable<decimal> total_non_fund_based_exposure { get; set; }
        public Nullable<decimal> total_utilization { get; set; }
        public Nullable<System.DateTime> trade_license_expiry_date { get; set; }
        public Nullable<System.DateTime> trade_license_issuance_date { get; set; }
        public string trade_license_number { get; set; }
        public Nullable<int> years_in_operation { get; set; }
        public string website { get; set; }
        public string twitter_id { get; set; }
        public Nullable<int> territory { get; set; }
        public Nullable<double> company_turnoveryear { get; set; }
        public Nullable<double> credit_turnover { get; set; }
        public Nullable<decimal> banks_ytd_revenue { get; set; }
        public Nullable<double> raroc { get; set; }
        public Nullable<int> address_type { get; set; }
        public Nullable<bool> blacklisted { get; set; }
        public Nullable<int> category { get; set; }
        public string client_id { get; set; }
        public Nullable<System.DateTime> date_of_establishment { get; set; }
        public Nullable<System.DateTime> date_of_last_contact { get; set; }
        public string enrollment_branch { get; set; }
        public Nullable<System.Guid> enrollment_branch_guid { get; set; }
        public Nullable<double> parent_company_ownership_perc { get; set; }
        public Nullable<decimal> gross_operating_margin { get; set; }
        public string flag { get; set; }
        public Nullable<int> owneridtype { get; set; }
        public string date_of_establishment_text { get; set; }
        public Nullable<int> product_detention { get; set; }
        public string alt_acct_exec_code { get; set; }
        public string credit_analyst { get; set; }
        public string alt_credit_analyst { get; set; }
        public Nullable<System.Guid> alt_acct_exec_code_guid { get; set; }
        public Nullable<System.Guid> credit_analyst_guid { get; set; }
        public Nullable<System.Guid> alt_credit_analyst_guid { get; set; }
        public string currency { get; set; }
        public Nullable<System.Guid> currency_guid { get; set; }
        public Nullable<bool> access_restrict_type { get; set; }
        public Nullable<System.Guid> corporategroup_guid { get; set; }
        public string owner { get; set; }
        public Nullable<System.Guid> owner_guid { get; set; }
    }
}
