//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrp_dependents
    {
        public int id_row { get; set; }
        public string Flag { get; set; }
        public string DependentName { get; set; }
        public Nullable<bool> ExistingCustomer { get; set; }
        public string IDType { get; set; }
        public string IDNumber { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Customer { get; set; }
        public string Relation { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string ParentCustomer { get; set; }
        public Nullable<System.Guid> IdTypeGuid { get; set; }
        public Nullable<System.Guid> CustomerGuid { get; set; }
        public Nullable<System.Guid> RelationGuid { get; set; }
        public Nullable<System.Guid> ParentCustomerGuid { get; set; }
        public Nullable<System.Guid> DependentPKGuid { get; set; }
        public string DomainName { get; set; }
        public Nullable<System.Guid> DomainNameGuid { get; set; }
        public Nullable<int> OwnerIDType { get; set; }
    }
}
