CREATE TABLE [dbo].[core_investment] (
    [id_row]                          INT            IDENTITY (1, 1) NOT NULL,
    [include_in_run]                  BIT            DEFAULT ((1)) NOT NULL,
    [investment_number]               NVARCHAR (100) NULL,
    [product]                         NVARCHAR (100) NULL,
    [product_group]                   NVARCHAR (100) NULL,
    [currency]                        NVARCHAR (100) NULL,
    [currency_type]                   INT            NULL,
    [security]                        NVARCHAR (100) NULL,
    [bank]                            NVARCHAR (100) NULL,
    [total_units]                     INT            NULL,
    [pledged_units]                   INT            NULL,
    [available_units]                 INT            NULL,
    [current_market_price]            MONEY          NULL,
    [current_ltv_perc]                FLOAT (53)     NULL,
    [allowed_ltv_perc]                FLOAT (53)     NULL,
    [weighted_price]                  MONEY          NULL,
    [acquisition_cost]                MONEY          NULL,
    [current_market_value]            FLOAT (53)     NULL,
    [profit_or_loss_perc]             FLOAT (53)     NULL,
    [current_price_date]              DATETIME       NULL,
    [type_of_investment]              NVARCHAR (100) NULL,
    [investor_profiling_performed]    NVARCHAR (100) NULL,
    [date_of_investor_profiling]      DATETIME       NULL,
    [investor_profiling_survey]       NVARCHAR (100) NULL,
    [date_of_next_investor_profiling] DATETIME       NULL,
    [asset_allocation_preferences]    NVARCHAR (100) NULL,
    [investment_objective]            NVARCHAR (100) NULL,
    [investment_experience]           NVARCHAR (100) NULL,
    [time_horizon]                    NVARCHAR (100) NULL,
    [liquidity_preference]            NVARCHAR (100) NULL,
    [growth_preference]               NVARCHAR (100) NULL,
    [has_investment_account]          BIT            NULL,
    [wealth_creation_objective]       NVARCHAR (100) NULL,
    [retirement_objective]            NVARCHAR (100) NULL,
    [safety_objective]                NVARCHAR (100) NULL,
    [risk_tolerance]                  NVARCHAR (100) NULL,
    [status]                          INT            NULL,
    [tenor]                           INT            NULL,
    [customer]                        NVARCHAR (100) NULL,
    [company]                         NVARCHAR (100) NULL,
    [flag]                            NCHAR (1)      NULL,
    [DomainName]                      NVARCHAR (50)  NULL,
    [OwnerIDType]                     INT            NULL
);

