CREATE TABLE [dbo].[core_credit_card] (
    [id_row]                         INT            IDENTITY (1, 1) NOT NULL,
    [include_in_run]                 BIT            DEFAULT ((1)) NOT NULL,
    [Flag]                           NCHAR (1)      NULL,
    [ActivationDate]                 DATE           NULL,
    [AvailableCashLimit]             MONEY          NULL,
    [AvailableLimit]                 MONEY          NULL,
    [Bank]                           NVARCHAR (100) NULL,
    [Branch]                         NVARCHAR (50)  NULL,
    [IsBundleCard]                   BIT            NULL,
    [CardLimit]                      MONEY          NULL,
    [CardType]                       INT            NULL,
    [CashLimit]                      MONEY          NULL,
    [IsCorporateCard]                INT            NULL,
    [Company]                        NVARCHAR (75)  NULL,
    [Customer]                       NVARCHAR (75)  NULL,
    [HolderCompany]                  NVARCHAR (75)  NULL,
    [HolderCustomer]                 NVARCHAR (75)  NULL,
    [Currency]                       NVARCHAR (50)  NULL,
    [CurrencyType]                   INT            NULL,
    [DelinquencyAmount]              MONEY          NULL,
    [DelinquencyStatus]              BIT            NULL,
    [EmbossingName]                  NVARCHAR (50)  NULL,
    [ExpiryDate]                     DATE           NULL,
    [LastPaymentDueDate]             DATE           NULL,
    [LastStatementBalance]           MONEY          NULL,
    [LastStatementDate]              DATE           NULL,
    [McbSecured]                     BIT            NULL,
    [MembershipRewardsPoint]         INT            NULL,
    [MinimumPaymentDue]              MONEY          NULL,
    [MonthlyPayment]                 NVARCHAR (50)  NULL,
    [NameoftheProductbundle]         NVARCHAR (100) NULL,
    [NextPaymentAmount]              MONEY          NULL,
    [NextPaymentDate]                DATE           NULL,
    [MaskedCardNumber]               NVARCHAR (50)  NULL,
    [OpeningDate]                    DATE           NULL,
    [OutstandingBalance]             MONEY          NULL,
    [PrimaryCardHolder]              NVARCHAR (50)  NULL,
    [Product]                        NVARCHAR (50)  NULL,
    [ProductGroup]                   NVARCHAR (50)  NULL,
    [ShadowAccountNumber]            NVARCHAR (50)  NULL,
    [Status]                         INT            NULL,
    [TemporaryCreditLimitAmount]     MONEY          NULL,
    [TemporaryCreditLimitExpiryDate] DATE           NULL,
    [UtilizedAmount]                 MONEY          NULL,
    [RepaymentAccount]               NVARCHAR (50)  NULL,
    [DomainName]                     NVARCHAR (50)  NULL,
    [OwnerIDType]                    INT            NULL
);

