CREATE TABLE [dbo].[core_debit_card] (
    [id_row]              INT            IDENTITY (1, 1) NOT NULL,
    [include_in_run]      BIT            DEFAULT ((1)) NOT NULL,
    [Flag]                NCHAR (1)      NULL,
    [ActivationDate]      DATE           NULL,
    [AvailableCashLimit]  MONEY          NULL,
    [AvailableLimit]      MONEY          NULL,
    [Bank]                NVARCHAR (100) NULL,
    [Branch]              NVARCHAR (50)  NULL,
    [IsBundleCard]        BIT            NULL,
    [CardType]            INT            NULL,
    [Company]             NVARCHAR (75)  NULL,
    [Currency]            NVARCHAR (50)  NULL,
    [CurrencyType]        INT            NULL,
    [Customer]            NVARCHAR (75)  NULL,
    [EmbossingName]       NVARCHAR (50)  NULL,
    [ExpiryDate]          DATE           NULL,
    [MaskedCardNumber]    NVARCHAR (50)  NULL,
    [OpeningDate]         DATE           NULL,
    [OutstandingBalance]  MONEY          NULL,
    [PrimaryCardHolder]   NVARCHAR (50)  NULL,
    [Product]             NVARCHAR (50)  NULL,
    [ProductGroup]        NVARCHAR (50)  NULL,
    [LinkedAccountNumber] NVARCHAR (50)  NULL,
    [Status]              INT            NULL,
    [DomainName]          NVARCHAR (50)  NULL,
    [OwnerIDType]         INT            NULL
);

