CREATE TABLE [dbo].[vrp_trade_finance_products] (
    [id_row]                           INT              NOT NULL,
    [flag]                             NCHAR (1)        NULL,
    [currency]                         NVARCHAR (50)    NULL,
    [GuidCurrency]                     UNIQUEIDENTIFIER NULL,
    [company]                          NVARCHAR (75)    NULL,
    [GuidCompany]                      UNIQUEIDENTIFIER NULL,
    [accountnumber]                    NVARCHAR (50)    NULL,
    [claimantbeneficiary]              NVARCHAR (200)   NULL,
    [claimantbeneficiary_guid]         UNIQUEIDENTIFIER NULL,
    [currencytype]                     INT              NULL,
    [customer]                         NVARCHAR (75)    NULL,
    [GuidCustomer]                     UNIQUEIDENTIFIER NULL,
    [product]                          NVARCHAR (50)    NULL,
    [GuidProduct]                      UNIQUEIDENTIFIER NULL,
    [productgroup]                     NVARCHAR (50)    NULL,
    [Guidproductgroup]                 UNIQUEIDENTIFIER NULL,
    [openingdate]                      DATE             NULL,
    [expirydate]                       DATE             NULL,
    [totalamount]                      MONEY            NULL,
    [beneficiarycountry]               NCHAR (3)        NULL,
    [GuidBeneficiarycountry]           UNIQUEIDENTIFIER NULL,
    [branch]                           NVARCHAR (50)    NULL,
    [GuidBranch]                       UNIQUEIDENTIFIER NULL,
    [totalamountinlocalcurrency]       MONEY            NULL,
    [outstandingamount]                MONEY            NULL,
    [outstandingamountinlocalcurrency] MONEY            NULL,
    [bank]                             NVARCHAR (100)   NULL,
    [Guidbank]                         UNIQUEIDENTIFIER NULL,
    [status]                           INT              NULL,
    [automaticrenewal]                 BIT              NULL,
    [beneficiaryname]                  NVARCHAR (200)   NULL,
    [GuidPrimarykey]                   UNIQUEIDENTIFIER NULL,
    [DomainName]                       NVARCHAR (50)    NULL,
    [OwnerIDType]                      INT              NULL,
    [DomainNameGuid]                   UNIQUEIDENTIFIER NULL
);

