CREATE TABLE [dbo].[vrp_credit_card_account] (
    [Flag]                           NCHAR (1)        NULL,
    [AvailableCashLimit]             DECIMAL (19, 4)  NULL,
    [AvailableLimit]                 DECIMAL (19, 4)  NULL,
    [Bank]                           NVARCHAR (100)   NULL,
    [Branch]                         NVARCHAR (50)    NULL,
    [IsBundleCard]                   BIT              NULL,
    [CardLimit]                      DECIMAL (19, 4)  NULL,
    [CashLimit]                      DECIMAL (19, 4)  NULL,
    [Company]                        NVARCHAR (75)    NULL,
    [Currency]                       NVARCHAR (50)    NULL,
    [CurrencyType]                   INT              NULL,
    [Customer]                       NVARCHAR (75)    NULL,
    [DelinquencyAmount]              DECIMAL (19, 4)  NULL,
    [DelinquencyStatus]              BIT              NULL,
    [ExpiryDate]                     DATETIME         NULL,
    [LastPaymentDueDate]             DATETIME         NULL,
    [LastStatementBalance]           DECIMAL (19, 4)  NULL,
    [LastStatementDate]              DATETIME         NULL,
    [MinimumPaymentDue]              DECIMAL (19, 4)  NULL,
    [MonthlyPayment]                 NVARCHAR (50)    NULL,
    [NextPaymentAmount]              DECIMAL (19, 4)  NULL,
    [NextPaymentDate]                DATETIME         NULL,
    [OpeningDate]                    DATETIME         NULL,
    [OutstandingBalance]             DECIMAL (19, 4)  NULL,
    [Product]                        NVARCHAR (50)    NULL,
    [ShadowAccountNumber]            NVARCHAR (50)    NULL,
    [Status]                         INT              NULL,
    [TemporaryCreditLimitAmount]     DECIMAL (19, 4)  NULL,
    [TemporaryCreditLimitExpiryDate] DATETIME         NULL,
    [UtilizedAmount]                 DECIMAL (19, 4)  NULL,
    [BankGuid]                       UNIQUEIDENTIFIER NULL,
    [BranchGuid]                     UNIQUEIDENTIFIER NULL,
    [CompanyGuid]                    UNIQUEIDENTIFIER NULL,
    [CurrencyGuid]                   UNIQUEIDENTIFIER NULL,
    [CustomerGuid]                   UNIQUEIDENTIFIER NULL,
    [ProductGuid]                    UNIQUEIDENTIFIER NULL,
    [ProductGroupGuid]               UNIQUEIDENTIFIER NULL,
    [DomainName]                     NVARCHAR (50)    NULL,
    [OwnerIDType]                    INT              NULL,
    [DomainNameGuid]                 UNIQUEIDENTIFIER NULL,
    [PrimaryKeyGuid]                 UNIQUEIDENTIFIER NULL,
    [OrderKey]                       INT              IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_vrp_credit_card_account] PRIMARY KEY CLUSTERED ([OrderKey] ASC)
);

