CREATE TABLE [dbo].[vrp_current_savings] (
    [Flag]                             NCHAR (1)        NULL,
    [AccountNumber]                    NVARCHAR (50)    NULL,
    [IsJoint]                          BIT              NULL,
    [Customer]                         NVARCHAR (75)    NULL,
    [ClaimantBeneficiary]              NVARCHAR (50)    NULL,
    [Branch]                           NVARCHAR (50)    NULL,
    [Bank]                             NVARCHAR (100)   NULL,
    [Currency]                         NVARCHAR (50)    NULL,
    [CurrencyType]                     NVARCHAR (50)    NULL,
    [BookBalance]                      DECIMAL (19, 4)  NULL,
    [BlockedFunds]                     DECIMAL (19, 4)  NULL,
    [BlockedAmount]                    DECIMAL (19, 4)  NULL,
    [BlockedReasons]                   NVARCHAR (4000)  NULL,
    [OdBaseRate]                       FLOAT (53)       NULL,
    [OdLimit]                          FLOAT (53)       NULL,
    [OdLimitCurrency]                  NVARCHAR (50)    NULL,
    [OpeningDate]                      DATETIME         NULL,
    [Product]                          NVARCHAR (50)    NULL,
    [ProductGroup]                     NVARCHAR (50)    NULL,
    [Status]                           INT              NULL,
    [UnclearedBalance]                 DECIMAL (19, 4)  NULL,
    [Company]                          NVARCHAR (75)    NULL,
    [AvailableBalance]                 DECIMAL (19, 4)  NULL,
    [AverageBalance]                   DECIMAL (19, 4)  NULL,
    [InitialDepositAmount]             DECIMAL (19, 4)  NULL,
    [SourceOfInitialDeposit]           NVARCHAR (200)   NULL,
    [SourceOfFunds]                    NVARCHAR (200)   NULL,
    [AccountSweep]                     BIT              NULL,
    [Compensation]                     BIT              NULL,
    [NoMonthlyCashTransactions]        INT              NULL,
    [VolOfCashTransactions]            DECIMAL (19, 4)  NULL,
    [NoMonthlyCashTransactions500KMur] INT              NULL,
    [NoMonthlyChequeTransaction]       INT              NULL,
    [VolOfChequeTransactions]          DECIMAL (19, 4)  NULL,
    [NoMonthlyCreditCardTransactions]  INT              NULL,
    [VolOfCreditCardTransactions]      DECIMAL (19, 4)  NULL,
    [NoMonthlyDebitCardTransactions]   INT              NULL,
    [VolOfDebitCardTransactions]       DECIMAL (19, 4)  NULL,
    [NoOfMonthlyInwardRemittances]     INT              NULL,
    [NoOfMonthlyOutwardRemittances]    INT              NULL,
    [NoOfMonthlySiTransactions]        INT              NULL,
    [VolOfSiTransactions]              DECIMAL (19, 4)  NULL,
    [NoOfMonthlyTtDdMcTransactions]    INT              NULL,
    [VolOfTtDdMcTransactions]          DECIMAL (19, 4)  NULL,
    [NumberOfUnpaidCheques]            INT              NULL,
    [ReturnedCheques]                  INT              NULL,
    [TransactionFrequency]             INT              NULL,
    [Carrier]                          NVARCHAR (50)    NULL,
    [CashCheques]                      INT              NULL,
    [ClearBalance]                     DECIMAL (19, 4)  NULL,
    [CounterPartyAccount]              NVARCHAR (50)    NULL,
    [LedgerBalance]                    DECIMAL (19, 4)  NULL,
    [LienAmount]                       DECIMAL (19, 4)  NULL,
    [Margin]                           DECIMAL (19, 4)  NULL,
    [OutOfOrderSince]                  DATETIME         NULL,
    [RateOfInterest]                   FLOAT (53)       NULL,
    [PenaltyInterest]                  FLOAT (53)       NULL,
    [BankGuid]                         UNIQUEIDENTIFIER NULL,
    [BranchGuid]                       UNIQUEIDENTIFIER NULL,
    [ClaimantGuid]                     UNIQUEIDENTIFIER NULL,
    [CompanyGuid]                      UNIQUEIDENTIFIER NULL,
    [CurrencyGuid]                     UNIQUEIDENTIFIER NULL,
    [CustomerGuid]                     UNIQUEIDENTIFIER NULL,
    [ProductGuid]                      UNIQUEIDENTIFIER NULL,
    [ProductGroupGuid]                 UNIQUEIDENTIFIER NULL,
    [PrimaryKeyGuid]                   UNIQUEIDENTIFIER NULL,
    [DomainName]                       NVARCHAR (50)    NULL,
    [OwnerIDType]                      INT              NULL,
    [DomainNameGuid]                   UNIQUEIDENTIFIER NULL,
    [OdLimitCurrencyGuid]              UNIQUEIDENTIFIER NULL,
    [OrderKey]                         BIGINT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_vrp_current_savings] PRIMARY KEY CLUSTERED ([OrderKey] ASC)
);

