CREATE TABLE [dbo].[vrp_loans_loans] (
    [id_row]                                   INT              NOT NULL,
    [flag]                                     NCHAR (1)        NULL,
    [account_balance]                          MONEY            NULL,
    [account_no]                               NVARCHAR (20)    NULL,
    [bank]                                     NVARCHAR (100)   NULL,
    [bank_guid]                                UNIQUEIDENTIFIER NULL,
    [claimant_beneficiary]                     NCHAR (10)       NULL,
    [claimant_beneficiary_guid]                UNIQUEIDENTIFIER NULL,
    [collection_risk]                          INT              NULL,
    [currency]                                 NCHAR (3)        NULL,
    [currency_guid]                            UNIQUEIDENTIFIER NULL,
    [currency_type]                            INT              NULL,
    [customer]                                 NCHAR (10)       NULL,
    [customer_guid]                            UNIQUEIDENTIFIER NULL,
    [debt_type]                                NVARCHAR (200)   NULL,
    [disbursed_amount]                         MONEY            NULL,
    [total_disbursement_amount]                MONEY            NULL,
    [disbursement_date]                        DATE             NULL,
    [down_payment]                             MONEY            NULL,
    [initial_loan_amount]                      MONEY            NULL,
    [installment_amount]                       MONEY            NULL,
    [interest_penalty_interest_amount_arrears] MONEY            NULL,
    [interest_amount]                          MONEY            NULL,
    [interest_rate]                            FLOAT (53)       NULL,
    [interest_rate_base_margin]                NVARCHAR (200)   NULL,
    [interest_repayment_amount]                MONEY            NULL,
    [interest_repayment_frequency]             NVARCHAR (100)   NULL,
    [is_early_repayment_allowed]               INT              NULL,
    [last_payment_amount]                      MONEY            NULL,
    [last_payment_date]                        DATE             NULL,
    [loan_maturity_date]                       DATE             NULL,
    [loan_number]                              NVARCHAR (20)    NULL,
    [loan_number_guid]                         UNIQUEIDENTIFIER NULL,
    [loan_start_date]                          DATE             NULL,
    [loan_type]                                INT              NULL,
    [next_installment_date]                    DATE             NULL,
    [next_payment_amount]                      MONEY            NULL,
    [next_payment_date]                        DATE             NULL,
    [original_amount]                          MONEY            NULL,
    [out_of_order_since]                       DATE             NULL,
    [outstanding_principal_amount]             MONEY            NULL,
    [outstanding_total_amount]                 MONEY            NULL,
    [payback_months]                           INT              NULL,
    [penalty_interest_rate]                    FLOAT (53)       NULL,
    [principal_amount]                         MONEY            NULL,
    [principal_amount_arrears]                 MONEY            NULL,
    [principal_repayment_amount]               MONEY            NULL,
    [principal_repayment_frequency]            NVARCHAR (100)   NULL,
    [product]                                  NVARCHAR (50)    NULL,
    [product_guid]                             UNIQUEIDENTIFIER NULL,
    [product_group]                            NVARCHAR (50)    NULL,
    [product_group_guid]                       UNIQUEIDENTIFIER NULL,
    [purpose_of_loan]                          NVARCHAR (200)   NULL,
    [rate_perc]                                FLOAT (53)       NULL,
    [restructuring]                            NCHAR (1)        NULL,
    [security_value]                           MONEY            NULL,
    [tenor]                                    INT              NULL,
    [status]                                   INT              NULL,
    [company]                                  NCHAR (10)       NULL,
    [company_guid]                             UNIQUEIDENTIFIER NULL,
    [outstanding_amount]                       MONEY            NULL,
    [amount_past_due]                          MONEY            NULL,
    [amount_past_due_interest]                 MONEY            NULL,
    [repayment_amount]                         MONEY            NULL,
    [repayment_frequency]                      NVARCHAR (100)   NULL,
    [arrears]                                  MONEY            NULL,
    [domain_name]                              NVARCHAR (16)    NULL,
    [domain_name_guid]                         UNIQUEIDENTIFIER NULL,
    [owneridtype]                              INT              NULL,
    [OrderKey]                                 BIGINT           IDENTITY (1, 1) NOT NULL
);



