CREATE TABLE [dbo].[vrp_credit_card] (
    [id_row]                         INT              NOT NULL,
    [Flag]                           NCHAR (1)        NULL,
    [ActivationDate]                 DATE             NULL,
    [AvailableCashLimit]             MONEY            NULL,
    [AvailableLimit]                 MONEY            NULL,
    [Bank]                           NVARCHAR (100)   NULL,
    [Bank_guid]                      UNIQUEIDENTIFIER NULL,
    [Branch]                         NVARCHAR (50)    NULL,
    [Branch_guid]                    UNIQUEIDENTIFIER NULL,
    [IsBundleCard]                   BIT              NULL,
    [CardLimit]                      MONEY            NULL,
    [CardType]                       INT              NULL,
    [CashLimit]                      MONEY            NULL,
    [IsCorporateCard]                INT              NULL,
    [Company]                        NVARCHAR (75)    NULL,
    [Company_guid]                   UNIQUEIDENTIFIER NULL,
    [Customer]                       NVARCHAR (75)    NULL,
    [Customer_guid]                  UNIQUEIDENTIFIER NULL,
    [HolderCompany]                  NVARCHAR (75)    NULL,
    [HolderCompany_guid]             UNIQUEIDENTIFIER NULL,
    [HolderCustomer]                 NVARCHAR (75)    NULL,
    [HolderCustomer_guid]            UNIQUEIDENTIFIER NULL,
    [Currency]                       NVARCHAR (50)    NULL,
    [Currency_guid]                  UNIQUEIDENTIFIER NULL,
    [CurrencyType]                   INT              NULL,
    [DelinquencyAmount]              MONEY            NULL,
    [DelinquencyStatus]              BIT              NULL,
    [EmbossingName]                  NVARCHAR (50)    NULL,
    [ExpiryDate]                     DATE             NULL,
    [LastPaymentDueDate]             DATE             NULL,
    [LastStatementBalance]           MONEY            NULL,
    [LastStatementDate]              DATE             NULL,
    [McbSecured]                     BIT              NULL,
    [MembershipRewardsPoint]         INT              NULL,
    [MinimumPaymentDue]              MONEY            NULL,
    [MonthlyPayment]                 NVARCHAR (50)    NULL,
    [NameoftheProductbundle]         NVARCHAR (100)   NULL,
    [NextPaymentAmount]              MONEY            NULL,
    [NextPaymentDate]                DATE             NULL,
    [MaskedCardNumber]               NVARCHAR (50)    NULL,
    [OpeningDate]                    DATE             NULL,
    [OutstandingBalance]             MONEY            NULL,
    [PrimaryCardHolder]              NVARCHAR (50)    NULL,
    [PrimaryCardHolder_guid]         UNIQUEIDENTIFIER NULL,
    [Product]                        NVARCHAR (50)    NULL,
    [Product_guid]                   UNIQUEIDENTIFIER NULL,
    [ProductGroup]                   NVARCHAR (50)    NULL,
    [ProductGroup_guid]              UNIQUEIDENTIFIER NULL,
    [ShadowAccountNumber]            NVARCHAR (50)    NULL,
    [ShadowAccountNumber_guid]       UNIQUEIDENTIFIER NULL,
    [Status]                         INT              NULL,
    [TemporaryCreditLimitAmount]     MONEY            NULL,
    [TemporaryCreditLimitExpiryDate] DATE             NULL,
    [UtilizedAmount]                 MONEY            NULL,
    [RepaymentAccount]               NVARCHAR (50)    NULL,
    [RepaymentAccount_Guid]          UNIQUEIDENTIFIER NULL,
    [DomainName]                     NVARCHAR (50)    NULL,
    [DomainName_guid]                UNIQUEIDENTIFIER NULL,
    [OwnerIDType]                    INT              NULL,
    [PrimaryKey_Guid]                UNIQUEIDENTIFIER NULL,
    [OrderKey]                       BIGINT           IDENTITY (1, 1) NOT NULL
);



