CREATE TABLE [dbo].[vrp_credit_card] (
    [Flag]                           NCHAR (1)        NULL,
    [ActivationDate]                 DATETIME         NULL,
    [AvailableCashLimit]             DECIMAL (19, 4)  NULL,
    [AvailableLimit]                 DECIMAL (19, 4)  NULL,
    [Bank]                           NVARCHAR (100)   NULL,
    [Bank_guid]                      UNIQUEIDENTIFIER NULL,
    [Branch]                         NVARCHAR (50)    NULL,
    [Branch_guid]                    UNIQUEIDENTIFIER NULL,
    [IsBundleCard]                   BIT              NULL,
    [CardLimit]                      DECIMAL (19, 4)  NULL,
    [CardType]                       INT              NULL,
    [CashLimit]                      DECIMAL (19, 4)  NULL,
    [Company]                        NVARCHAR (75)    NULL,
    [Company_guid]                   UNIQUEIDENTIFIER NULL,
    [Customer]                       NVARCHAR (75)    NULL,
    [Customer_guid]                  UNIQUEIDENTIFIER NULL,
    [HolderCompany]                  NVARCHAR (75)    NULL,
    [HolderCompany_guid]             UNIQUEIDENTIFIER NULL,
    [HolderCustomer]                 NVARCHAR (75)    NULL,
    [HolderCustomer_guid]            UNIQUEIDENTIFIER NULL,
    [Currency]                       NVARCHAR (50)    NULL,
    [Currency_guid]                  UNIQUEIDENTIFIER NULL,
    [CurrencyType]                   INT              NULL,
    [DelinquencyAmount]              DECIMAL (19, 4)  NULL,
    [DelinquencyStatus]              BIT              NULL,
    [EmbossingName]                  NVARCHAR (50)    NULL,
    [ExpiryDate]                     DATETIME         NULL,
    [LastPaymentDueDate]             DATETIME         NULL,
    [LastStatementBalance]           DECIMAL (19, 4)  NULL,
    [LastStatementDate]              DATETIME         NULL,
    [McbSecured]                     BIT              NULL,
    [MembershipRewardsPoint]         INT              NULL,
    [MinimumPaymentDue]              DECIMAL (19, 4)  NULL,
    [MonthlyPayment]                 NVARCHAR (50)    NULL,
    [NameoftheProductbundle]         NVARCHAR (100)   NULL,
    [NextPaymentAmount]              DECIMAL (19, 4)  NULL,
    [NextPaymentDate]                DATETIME         NULL,
    [MaskedCardNumber]               NVARCHAR (50)    NULL,
    [OpeningDate]                    DATETIME         NULL,
    [OutstandingBalance]             DECIMAL (19, 4)  NULL,
    [PrimaryCardHolder]              NVARCHAR (50)    NULL,
    [PrimaryCardHolder_guid]         UNIQUEIDENTIFIER NULL,
    [Product]                        NVARCHAR (50)    NULL,
    [Product_guid]                   UNIQUEIDENTIFIER NULL,
    [ProductGroup]                   NVARCHAR (50)    NULL,
    [ProductGroup_guid]              UNIQUEIDENTIFIER NULL,
    [ShadowAccountNumber]            NVARCHAR (50)    NULL,
    [ShadowAccountNumber_guid]       UNIQUEIDENTIFIER NULL,
    [Status]                         INT              NULL,
    [TemporaryCreditLimitAmount]     DECIMAL (19, 4)  NULL,
    [TemporaryCreditLimitExpiryDate] DATETIME         NULL,
    [UtilizedAmount]                 DECIMAL (19, 4)  NULL,
    [DomainName]                     NVARCHAR (50)    NULL,
    [DomainName_guid]                UNIQUEIDENTIFIER NULL,
    [OwnerIDType]                    INT              NULL,
    [PrimaryKey_Guid]                UNIQUEIDENTIFIER NULL,
    [OrderKey]                       BIGINT           IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_vrp_credit_card] PRIMARY KEY CLUSTERED ([OrderKey] ASC)
);

