CREATE TABLE [dbo].[vrp_debit_card] (
    [id_row]                   INT              NOT NULL,
    [PrimaryKey_guid]          UNIQUEIDENTIFIER NULL,
    [Flag]                     NCHAR (1)        NULL,
    [ActivationDate]           DATE             NULL,
    [AvailableCashLimit]       MONEY            NULL,
    [AvailableLimit]           MONEY            NULL,
    [Bank]                     NVARCHAR (100)   NULL,
    [Bank_guid]                UNIQUEIDENTIFIER NULL,
    [Branch]                   NVARCHAR (50)    NULL,
    [Branch_guid]              UNIQUEIDENTIFIER NULL,
    [IsBundleCard]             BIT              NULL,
    [CardType]                 INT              NULL,
    [Company]                  NVARCHAR (75)    NULL,
    [Company_guid]             UNIQUEIDENTIFIER NULL,
    [Currency]                 NVARCHAR (50)    NULL,
    [Currency_guid]            UNIQUEIDENTIFIER NULL,
    [CurrencyType]             INT              NULL,
    [Customer]                 NVARCHAR (75)    NULL,
    [Customer_guid]            UNIQUEIDENTIFIER NULL,
    [EmbossingName]            NVARCHAR (50)    NULL,
    [ExpiryDate]               DATE             NULL,
    [MaskedCardNumber]         NVARCHAR (50)    NULL,
    [OpeningDate]              DATE             NULL,
    [OutstandingBalance]       MONEY            NULL,
    [PrimaryCardHolder]        NVARCHAR (50)    NULL,
    [PrimaryCardHolder_guid]   UNIQUEIDENTIFIER NULL,
    [Product]                  NVARCHAR (50)    NULL,
    [Product_guid]             UNIQUEIDENTIFIER NULL,
    [ProductGroup]             NVARCHAR (50)    NULL,
    [ProductGroup_guid]        UNIQUEIDENTIFIER NULL,
    [LinkedAccountNumber]      NVARCHAR (50)    NULL,
    [LinkedAccountNumber_guid] UNIQUEIDENTIFIER NULL,
    [Status]                   INT              NULL,
    [DomainName]               NVARCHAR (50)    NULL,
    [DomainName_guid]          UNIQUEIDENTIFIER NULL,
    [OwnerIDType]              INT              NULL,
    [OrderKey]                 BIGINT           IDENTITY (1, 1) NOT NULL
);



