CREATE TABLE [dbo].[vrp_bank_assurance] (
    [id_row]                      INT              NOT NULL,
    [flag]                        NCHAR (1)        NULL,
    [ins_policy_id]               NVARCHAR (100)   NULL,
    [type]                        INT              NULL,
    [policy_name]                 NVARCHAR (100)   NULL,
    [contract_date]               DATE             NULL,
    [maturity_date]               DATE             NULL,
    [ccy_code]                    NCHAR (3)        NULL,
    [ccy_code_guid]               UNIQUEIDENTIFIER NULL,
    [ccy_type]                    INT              NULL,
    [amount]                      MONEY            NULL,
    [customer_main_insured]       NCHAR (10)       NULL,
    [customer_main_insured_guid]  UNIQUEIDENTIFIER NULL,
    [company_main_insured]        NCHAR (10)       NULL,
    [company_main_insured_guid]   UNIQUEIDENTIFIER NULL,
    [customer_joint_insured]      NCHAR (10)       NULL,
    [customer_joint_insured_guid] UNIQUEIDENTIFIER NULL,
    [company_joint_insured]       NCHAR (10)       NULL,
    [company_joint_insured_guid]  UNIQUEIDENTIFIER NULL,
    [bank]                        NCHAR (10)       NULL,
    [bank_guid]                   UNIQUEIDENTIFIER NULL,
    [status]                      INT              NULL,
    [policy_number]               NVARCHAR (500)   NULL,
    [product]                     NVARCHAR (50)    NULL,
    [product_guid]                UNIQUEIDENTIFIER NULL,
    [product_group]               NVARCHAR (50)    NULL,
    [product_group_guid]          UNIQUEIDENTIFIER NULL,
    [sum_insured]                 MONEY            NULL,
    [insurance_company]           NCHAR (10)       NULL,
    [insurance_company_guid]      UNIQUEIDENTIFIER NULL,
    [owner]                       NVARCHAR (50)    NULL,
    [owneridtype]                 INT              NULL,
    [primary_key]                 UNIQUEIDENTIFIER NULL
);

