CREATE TABLE [dbo].[vrp_corporate_customer] (
    [cif]                            NVARCHAR (100)   NOT NULL,
    [cif_guid]                       UNIQUEIDENTIFIER NULL,
    [county]                         NVARCHAR (100)   NULL,
    [line_1]                         NVARCHAR (100)   NULL,
    [line_2]                         NVARCHAR (100)   NULL,
    [line_3]                         NVARCHAR (100)   NULL,
    [zip_postal_code]                NVARCHAR (100)   NULL,
    [post_office_box]                NVARCHAR (100)   NULL,
    [state_province]                 NVARCHAR (100)   NULL,
    [do_not_allow_bulk_emails]       BIT              NULL,
    [do_not_allow_emails]            BIT              NULL,
    [do_not_allow_faxes]             BIT              NULL,
    [do_not_allow_phone_calls]       BIT              NULL,
    [do_not_allow_mails]             BIT              NULL,
    [send_marketing_materials]       BIT              NULL,
    [email]                          NVARCHAR (100)   NULL,
    [fax]                            NVARCHAR (100)   NULL,
    [industry]                       INT              NULL,
    [last_date_included_in_campaign] DATETIME         NULL,
    [company_name]                   NVARCHAR (100)   NULL,
    [no_of_employees]                INT              NULL,
    [originating_lead]               NVARCHAR (50)    NULL,
    [originating_lead_guid]          UNIQUEIDENTIFIER NULL,
    [ownership]                      INT              NULL,
    [parent_company]                 NVARCHAR (50)    NULL,
    [parent_company_guid]            UNIQUEIDENTIFIER NULL,
    [preferred_method_of_contact]    INT              NULL,
    [primary_contact]                NVARCHAR (50)    NULL,
    [primary_contact_guid]           UNIQUEIDENTIFIER NULL,
    [main_phone]                     NVARCHAR (100)   NULL,
    [ticker_symbol]                  NVARCHAR (100)   NULL,
    [city]                           NVARCHAR (50)    NULL,
    [city_guid]                      UNIQUEIDENTIFIER NULL,
    [company_turnover_month]         FLOAT (53)       NULL,
    [corporate_segment]              NVARCHAR (50)    NULL,
    [corporate_segment_guid]         UNIQUEIDENTIFIER NULL,
    [fitch_long_term]                INT              NULL,
    [fitch_short_term]               INT              NULL,
    [in_liquidation]                 BIT              NULL,
    [last_interaction_date]          DATETIME         NULL,
    [moody_long_term]                INT              NULL,
    [moody_short_term]               INT              NULL,
    [no_of_offices_branches]         INT              NULL,
    [number_of_active_products]      INT              NULL,
    [number_of_products]             INT              NULL,
    [operation_mode]                 INT              NULL,
    [relationship_manager]           NVARCHAR (50)    NULL,
    [relationship_manager_guid]      UNIQUEIDENTIFIER NULL,
    [relationship_status]            INT              NULL,
    [sector]                         NVARCHAR (50)    NULL,
    [sector_guid]                    UNIQUEIDENTIFIER NULL,
    [special_codes]                  NVARCHAR (100)   NULL,
    [s_and_p_long_term]              INT              NULL,
    [s_and_p_short_term]             INT              NULL,
    [total_fund_based_exposure]      DECIMAL (19, 4)  NULL,
    [total_limits]                   DECIMAL (19, 4)  NULL,
    [total_credit]                   DECIMAL (19, 4)  NULL,
    [total_non_fund_based_exposure]  DECIMAL (19, 4)  NULL,
    [total_utilization]              DECIMAL (19, 4)  NULL,
    [trade_license_expiry_date]      DATETIME         NULL,
    [trade_license_issuance_date]    DATETIME         NULL,
    [trade_license_number]           NVARCHAR (100)   NULL,
    [years_in_operation]             INT              NULL,
    [website]                        NVARCHAR (100)   NULL,
    [twitter_id]                     NVARCHAR (100)   NULL,
    [territory]                      INT              NULL,
    [company_turnoveryear]           FLOAT (53)       NULL,
    [credit_turnover]                FLOAT (53)       NULL,
    [banks_ytd_revenue]              DECIMAL (32, 6)  NULL,
    [raroc]                          FLOAT (53)       NULL,
    [address_type]                   INT              NULL,
    [blacklisted]                    BIT              NULL,
    [category]                       INT              NULL,
    [client_id]                      NVARCHAR (100)   NULL,
    [date_of_establishment]          DATETIME         NULL,
    [date_of_last_contact]           DATETIME         NULL,
    [enrollment_branch]              NVARCHAR (50)    NULL,
    [enrollment_branch_guid]         UNIQUEIDENTIFIER NULL,
    [parent_company_ownership_perc]  FLOAT (53)       NULL,
    [gross_operating_margin]         DECIMAL (32, 6)  NULL,
    [flag]                           NVARCHAR (1)     NULL,
    [owneridtype]                    INT              NULL,
    [date_of_establishment_text]     NVARCHAR (50)    NULL,
    [product_detention]              INT              NULL,
    [alt_acct_exec_code]             NVARCHAR (50)    NULL,
    [credit_analyst]                 NVARCHAR (50)    NULL,
    [alt_credit_analyst]             NVARCHAR (50)    NULL,
    [alt_acct_exec_code_guid]        UNIQUEIDENTIFIER NULL,
    [credit_analyst_guid]            UNIQUEIDENTIFIER NULL,
    [alt_credit_analyst_guid]        UNIQUEIDENTIFIER NULL,
    [currency]                       NCHAR (3)        NULL,
    [currency_guid]                  UNIQUEIDENTIFIER NULL,
    [access_restrict_type]           BIT              NULL,
    [corporategroup_guid]            UNIQUEIDENTIFIER NULL,
    [owner]                          NVARCHAR (50)    NULL,
    [owner_guid]                     UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_vrp_corporate_customer] PRIMARY KEY CLUSTERED ([cif] ASC)
);

