GO
insert into app_package(level_id, package_type, package_name) values
(	1	,	'MASTER'	,	'City'	),
(	2	,	'MASTER'	,	'Product'	),
(	4	,	'MASTER'	,	'Sector'	),
(	8	,	'MASTER'	,	'RetailSegment'	),
(	9	,	'MASTER'	,	'CorporateSegment'	),
(	12	,	'CRM'	,	'Retail Customer'	),
(	13	,	'CRM'	,	'CorporateCustomer(Account)'	),
(	14	,	'CRM'	,	'CASA'	),
(	15	,	'CRM'	,	'FixedDeposit'	),
(	16	,	'CRM'	,	'Credit Card'	),
(	17	,	'CRM'	,	'Debit Card'	),
(	18	,	'CRM'	,	'Loan (CustomerProduct)'	),
(	19	,	'CRM'	,	'Loan Guarantor'	),
(	21	,	'CRM'	,	'Loan Co Borrower'	),
(	22	,	'CRM'	,	'Investments'	),
(	23	,	'CRM'	,	'TradeFinance(CustomerProduct)'	),
(	24	,	'CRM'	,	'Joint Account (CustomerProduct)'	),
(	25	,	'CRM'	,	'PowerOfAttorney'	),
(	26	,	'CRM'	,	'Dependent'	),
(	27	,	'CRM'	,	'Collateral'	),
(	28	,	'CRM'	,	'Enrolled Services (Retail)'	),
(	29	,	'CRM'	,	'Enrolled Services Linked Accts'	),
(	30	,	'CRM'	,	'ShareHolders'	),
(	31	,	'CRM'	,	'POS Machines'	),
(	32	,	'CRM'	,	'Customer Interaction'	),
(	34	,	'CRM'	,	'Credit Card Account'	),
(	35	,	'CRM'	,	'SalesProcess'	),
(	36	,	'CRM'	,	'Connection Joint Account'	),
(	37	,	'CRM'	,	'Connection Co Borrower'	),
(	38	,	'CRM'	,	'Connection Co Guarantor'	),
(	39	,	'CRM'	,	'FosOpportunity'	),
(	40	,	'CRM'	,	'Retail Prospect'	),
(	41	,	'CRM'	,	'Corporate Prospect'	),
(	42	,	'CRM'	,	'CampaignResponse'	),
(	43	,	'CRM'	,	'Treasury (CustomerProduct)'	),
(	44	,	'CRM'	,	'Enrolled Services (Corporate)'	),
(	45	,	'MASTER'	,	'Currency'	),
(	46	,	'CRM'	,	'Outlet'	),
(	47	,	'CRM'	,	'Outlet Transactions Summary'	),
(	48	,	'CRM'	,	'Alert'	),
(	49	,	'CRM'	,	'Corporate Group'	),
(	50	,	'CRM'	,	'Corporate Raroc'	),
(	51	,	'CRM'	,	'Corporate Moodys'	),
(	52	,	'CRM'	,	'Fos Loan Disbursement'	),
(	53	,	'CRM'	,	'Bank Assurance (CustomerProduct)'	),
(	54	,	'IRM'	,	'IRM FEED'	),
(	55	,	'DB2'	,	'Db2Integration'	),
(	56	,	'DB2'	,	'Db2IntegrationCore'	),
